<?php

namespace Database\Seeders;

use App\Models\Industry;
use Illuminate\Database\Seeder;

class IndustrySeeder extends Seeder
{
    public function run(): void
    {
        $industries = [
            [
                'name' => 'Financial Services',
                'code' => 'financial_services',
                'description' => 'Banking, insurance, investment, and financial advisory services',
                'icon' => '🏦',
                'color' => '#059669',
                'sic_codes' => ['64', '65', '66'],
                'typical_compliance_requirements' => ['FICA', 'POPIA', 'FSB Regulations', 'SARS'],
                'requires_fica' => true,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 45,
                'common_document_types' => ['FICA Documents', 'Proof of Income', 'Bank Statements', 'ID Documents'],
                'regulatory_bodies' => ['Financial Sector Conduct Authority (FSCA)', 'Prudential Authority', 'SARS'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Healthcare & Medical Services',
                'code' => 'healthcare',
                'description' => 'Medical practices, hospitals, pharmaceuticals, and health services',
                'icon' => '🏥',
                'color' => '#dc2626',
                'sic_codes' => ['86', '87', '88'],
                'typical_compliance_requirements' => ['HPCSA', 'POPIA', 'Medical Schemes Act'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 21,
                'common_document_types' => ['Medical Records', 'Consent Forms', 'Insurance Claims', 'Patient Information'],
                'regulatory_bodies' => ['Health Professions Council of SA', 'Department of Health', 'Medical Schemes Authority'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Education & Training',
                'code' => 'education',
                'description' => 'Schools, universities, training institutions, and educational services',
                'icon' => '🎓',
                'color' => '#2563eb',
                'sic_codes' => ['85'],
                'typical_compliance_requirements' => ['POPIA', 'SACE', 'Department of Education'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 30,
                'common_document_types' => ['Student Records', 'Certificates', 'Enrollment Forms', 'Academic Transcripts'],
                'regulatory_bodies' => ['Department of Basic Education', 'Department of Higher Education', 'SACE'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Mining & Resources',
                'code' => 'mining',
                'description' => 'Mining operations, mineral extraction, and natural resources',
                'icon' => '⛏️',
                'color' => '#92400e',
                'sic_codes' => ['05', '06', '07', '08', '09'],
                'typical_compliance_requirements' => ['Mining Charter', 'POPIA', 'DMRE Regulations', 'Environmental Compliance'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 60,
                'common_document_types' => ['Mining Licenses', 'Environmental Impact', 'Safety Certificates', 'BEE Certificates'],
                'regulatory_bodies' => ['Department of Mineral Resources and Energy', 'Mine Health and Safety Inspectorate'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Manufacturing',
                'code' => 'manufacturing',
                'description' => 'Production, assembly, and manufacturing of goods',
                'icon' => '🏭',
                'color' => '#7c3aed',
                'sic_codes' => ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33'],
                'typical_compliance_requirements' => ['POPIA', 'SABS Standards', 'Environmental Compliance', 'Labour Relations'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 35,
                'common_document_types' => ['Quality Certificates', 'Safety Documents', 'Product Specifications', 'Compliance Reports'],
                'regulatory_bodies' => ['SABS', 'Department of Employment and Labour', 'Department of Trade and Industry'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Agriculture & Agribusiness',
                'code' => 'agriculture',
                'description' => 'Farming, livestock, agricultural processing, and related services',
                'icon' => '🌾',
                'color' => '#16a34a',
                'sic_codes' => ['01', '02', '03'],
                'typical_compliance_requirements' => ['POPIA', 'Department of Agriculture', 'Land Reform Compliance'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 25,
                'common_document_types' => ['Land Certificates', 'Agricultural Permits', 'Livestock Records', 'Crop Reports'],
                'regulatory_bodies' => ['Department of Agriculture, Land Reform and Rural Development'],
                'sort_order' => 6,
            ],
            [
                'name' => 'Information Technology',
                'code' => 'technology',
                'description' => 'Software development, IT services, telecommunications, and digital solutions',
                'icon' => '💻',
                'color' => '#0891b2',
                'sic_codes' => ['58', '59', '60', '61', '62', '63'],
                'typical_compliance_requirements' => ['POPIA', 'ICASA Regulations', 'Cybersecurity Compliance'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 20,
                'common_document_types' => ['Software Licenses', 'Security Certificates', 'Data Processing Agreements', 'Technical Specifications'],
                'regulatory_bodies' => ['ICASA', 'Department of Communications and Digital Technologies'],
                'sort_order' => 7,
            ],
            [
                'name' => 'Construction & Engineering',
                'code' => 'construction',
                'description' => 'Building construction, civil engineering, and infrastructure development',
                'icon' => '🏗️',
                'color' => '#ea580c',
                'sic_codes' => ['41', '42', '43'],
                'typical_compliance_requirements' => ['POPIA', 'NHBRC', 'Construction Industry Development Board'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 45,
                'common_document_types' => ['Building Plans', 'Safety Certificates', 'Material Specifications', 'Project Permits'],
                'regulatory_bodies' => ['NHBRC', 'Construction Industry Development Board', 'Department of Public Works'],
                'sort_order' => 8,
            ],
            [
                'name' => 'Transportation & Logistics',
                'code' => 'logistics',
                'description' => 'Transportation services, logistics, freight, and supply chain management',
                'icon' => '🚚',
                'color' => '#4338ca',
                'sic_codes' => ['49', '50', '51', '52', '53'],
                'typical_compliance_requirements' => ['POPIA', 'Department of Transport', 'Road Traffic Management'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 30,
                'common_document_types' => ['Transport Licenses', 'Vehicle Certificates', 'Driver Records', 'Cargo Manifests'],
                'regulatory_bodies' => ['Department of Transport', 'Road Traffic Management Corporation'],
                'sort_order' => 9,
            ],
            [
                'name' => 'Retail & E-commerce',
                'code' => 'retail',
                'description' => 'Retail trade, e-commerce, wholesale, and consumer services',
                'icon' => '🛍️',
                'color' => '#db2777',
                'sic_codes' => ['45', '46', '47'],
                'typical_compliance_requirements' => ['POPIA', 'Consumer Protection Act', 'Competition Commission'],
                'requires_fica' => false,
                'requires_bee_compliance' => true,
                'typical_workflow_duration_days' => 25,
                'common_document_types' => ['Product Catalogs', 'Invoice Records', 'Customer Data', 'Supplier Agreements'],
                'regulatory_bodies' => ['Competition Commission', 'National Consumer Commission'],
                'sort_order' => 10,
            ],
        ];

        foreach ($industries as $industry) {
            Industry::firstOrCreate(
                ['code' => $industry['code']],
                $industry
            );
        }

        $this->command->info('✅ South African industries seeded successfully');
    }
}
